WebApplication1/Models/Calendar.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public class Calendar
    {
        [Key]
        public int ID { get; set; }

        [Required, DisplayName("日期"), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime date { get; set; }

        [DisplayName("日期名稱")]
        public string name { get; set; }

        [Required, DisplayName("是否放假")]
        public string isHoliday { get; set; }

        [Required, DisplayName("日期類別")]
        public string holidayCategory { get; set; }

        [DisplayName("日期描述")]
        public string description { get; set; }
    }
}

WebApplication1/Controllers/CalendarsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using LinqToExcel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml.FormulaParsing.Excel.Functions.DateTime;
using WebApplication1.Models;

namespace WebApplication1.Views
{
    public class CalendarsController : Controller
    {
        private readonly WebApplication1Context _context;
        private readonly string _folder;
        public CalendarsController(WebApplication1Context context, IHostingEnvironment env)
        {
            _context = context;
            // 把上傳目錄設為：wwwroot\UploadFolder
            _folder = $@"{env.WebRootPath}\UploadFolder";
        }

        // GET: Calendars
        public async Task<IActionResult> Index()
        {
            return View(await _context.Calendar.ToListAsync());
        }

        //回傳Json
        public async Task<IActionResult> JSONdata()
        {
            return Json(await _context.Calendar.ToListAsync());
        }

        // GET: Calendars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var calendar = await _context.Calendar
                .SingleOrDefaultAsync(m => m.ID == id);
            if (calendar == null)
            {
                return NotFound();
            }

            return View(calendar);
        }

        // GET: Calendars/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Calendars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,date,name,isHoliday,holidayCategory,description")] Calendar calendar)
        {
            if (ModelState.IsValid)
            {
                _context.Add(calendar);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(calendar);
        }

        // GET: Calendars/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var calendar = await _context.Calendar.SingleOrDefaultAsync(m => m.ID == id);
            if (calendar == null)
            {
                return NotFound();
            }
            return View(calendar);
        }

        // POST: Calendars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,date,name,isHoliday,holidayCategory,description")] Calendar calendar)
        {
            if (id != calendar.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(calendar);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CalendarExists(calendar.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(calendar);
        }

        // GET: Calendars/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var calendar = await _context.Calendar
                .SingleOrDefaultAsync(m => m.ID == id);
            if (calendar == null)
            {
                return NotFound();
            }

            return View(calendar);
        }

        // POST: Calendars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var calendar = await _context.Calendar.SingleOrDefaultAsync(m => m.ID == id);
            _context.Calendar.Remove(calendar);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost("UploadFiles")]
        public async Task<IActionResult> Post(List<IFormFile> files)
        {
            //上傳檔案
            if (files.Count < 1)
            {
                return Ok("請選擇檔案，並確定檔案為csv檔。");
            }

            foreach (var file in files)
            {
                if (file.Length > 0)
                {
                    //儲存檔案
                    var filePath = $@"{_folder}\{file.FileName}";
                    try
                    {
                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await file.CopyToAsync(stream);
                        }
                    }
                    catch (Exception ex)
                    {
                        return Ok("無法儲存檔案到資料庫，請確定您所輸入的檔案(" + file.FileName + ")，沒有被其他應用程式所開啟或應用。");
                    }
                    
                   
                    //讀取csv檔案
                    var count_line = 0;
                    
                    StreamReader sr = new StreamReader(filePath, Encoding.GetEncoding("Big5"));
                    while (!sr.EndOfStream) // 每次讀取一行，直到檔尾
                    {
                        bool file_success = true;
                        string line = sr.ReadLine();// 讀取文字到 line 變數    
                        string[] dataArray = new string[5];
                        String match_date, match_name, match_isHoliday, match_holidayCategory, match_description;
                        
                        // 判斷第一行是否為正確格式
                        if (count_line == 0 && (line != "\"date\",\"name\",\"isHoliday\",\"holidayCategory\",\"description\"" && line != "date\tname\tisHoliday\tholidayCategory\tdescription"))
                        {
                            return Ok("請確定資料格式是否正確，是否第一列為date、name、isHoliday、holidayCategory、description，並確定檔案為csv檔。");
                        }

                        //有時候csv進行另存時會更改格式，改用tab分割。
                        try
                        {
                            dataArray = line.Split(',');
                            match_date = dataArray[0].Replace("\"", "");
                            match_name = dataArray[1].Replace("\"", "");
                            match_isHoliday = dataArray[2].Replace("\"", "");
                            match_holidayCategory = dataArray[3].Replace("\"", "");
                            match_description = dataArray[4].Replace("\"", "");
                        }
                        catch (Exception ex)
                        {
                            dataArray = line.Split('\t');
                            match_date = dataArray[0].Replace("\"", "");
                            match_name = dataArray[1].Replace("\"", "");
                            match_isHoliday = dataArray[2].Replace("\"", "");
                            match_holidayCategory = dataArray[3].Replace("\"", "");
                            match_description = dataArray[4].Replace("\"", "");
                        }

                        //跳過空白行
                        if (line == ",,,," || line == "\t\t\t\t") file_success = false;

                        if (count_line > 0 && file_success == true)
                        {
                            //確定必填值是否都有資料
                            if (match_date == "") return Ok("請確定輸入的檔案(" + file.FileName + ")第" + count_line + "行的date是不有填寫。");
                            if (match_isHoliday != "是" && match_isHoliday != "否") return Ok("請確定輸入的檔案(" + file.FileName + ")第" + count_line + "行的isHoliday是不有填寫是或否。");
                            if (match_holidayCategory == "") return Ok("請確定輸入的檔案(" + file.FileName + ")第" + count_line + "行的holidayCategory是不有填寫。");
                        }
                        
                        //判斷資料是否格式正確，正確就add一行
                        if (count_line != 0 && file_success == true)
                        {                          
                            try
                            {
                                //將日期正規化
                                DateTime match_date_D = DateTime.ParseExact(dataArray[0].Replace("\"", ""), "yyyy/M/d", System.Globalization.CultureInfo.InvariantCulture);
                                
                                //確定資料庫是否有重複資料，沒有則新增，重複則更新資料
                                if (!CalendarDateExists(match_date_D))
                                {
                                    _context.Calendar.Add(new Calendar()
                                    {
                                        date = match_date_D,
                                        name = match_name,
                                        isHoliday = match_isHoliday,
                                        holidayCategory = match_holidayCategory,
                                        description = match_description
                                    });
                                }
                                else
                                {
                                    _context.Update(new Calendar()

WebApplication1/Views/Calendars/Create.cshtml
@model WebApplication1.Models.Calendar

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Calendar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="date" class="control-label"></label>
                <input asp-for="date" class="form-control" />
                <span asp-validation-for="date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="isHoliday" class="control-label"></label>
                <input asp-for="isHoliday" class="form-control" />
                <span asp-validation-for="isHoliday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="holidayCategory" class="control-label"></label>
                <input asp-for="holidayCategory" class="form-control" />
                <span asp-validation-for="holidayCategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="description" class="control-label"></label>
                <input asp-for="description" class="form-control" />
                <span asp-validation-for="description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Views/Calendars/Delete.cshtml
@model WebApplication1.Models.Calendar

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Calendar</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.isHoliday)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.isHoliday)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.holidayCategory)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.holidayCategory)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication1/Views/Calendars/Details.cshtml
@model WebApplication1.Models.Calendar

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Calendar</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.isHoliday)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.isHoliday)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.holidayCategory)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.holidayCategory)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication1/Views/Calendars/Edit.cshtml
@model WebApplication1.Models.Calendar

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Calendar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="date" class="control-label"></label>
                <input asp-for="date" class="form-control" />
                <span asp-validation-for="date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="isHoliday" class="control-label"></label>
                <input asp-for="isHoliday" class="form-control" />
                <span asp-validation-for="isHoliday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="holidayCategory" class="control-label"></label>
                <input asp-for="holidayCategory" class="form-control" />
                <span asp-validation-for="holidayCategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="description" class="control-label"></label>
                <input asp-for="description" class="form-control" />
                <span asp-validation-for="description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Views/Calendars/Index.cshtml
@model IEnumerable<WebApplication1.Models.Calendar>

@{
    ViewData["Title"] = "Index";
}


<h2>檔案上傳</h2>


<form method="post" enctype="multipart/form-data" asp-controller="UploadFiles" asp-action="Index">
    <div class="form-group">
        <div class="col-md-10">
            <p>從政府部門<a href="https://data.gov.tw/dataset/26557">下載</a>一csv檔，並上傳至此。</p>
            <input type="file" name="files" accept=".csv" onchange="checkfile(this);" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="上傳"  />
        </div>
    </div>
</form>



<div id='jqxWidget'></div>
<script>

    $("#jqxWidget").jqxCalendar({
        enableTooltips: true,
        width: 220,
        height: 220
    });
    function update_Calendar() {
             $.ajax({
            type: 'GET',
            url: "@Url.Action("JSONdata", "Calendars")",
            data: { get_param: 'value' },
            dataType: 'json',
            async: false,
            success: function (data) {
               for (var i = 1; i < data.length; i++) {
                   if (data[i].isHoliday == '是') {
                       $("#jqxWidget").jqxCalendar('addSpecialDate', new Date(data[i].date), '', data[i].holidayCategory);
                   }
               }
            }
            });
    }
    update_Calendar()
    function checkfile(sender) {

        // 可接受的附檔名
        var validExts = new Array(".csv");

        var fileExt = sender.value;
        fileExt = fileExt.substring(fileExt.lastIndexOf('.'));
        if (validExts.indexOf(fileExt) < 0) {
            alert("檔案類型錯誤，可接受的副檔名有：" + validExts.toString());
            sender.value = null;
            return false;
        }
        else return true;
    }

</script>